# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Built and UI test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_ui_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo on the runner
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: 2-SeleniumIDE
      - name: Build
        run: dotnet build --no-restore
        working-directory: 2-SeleniumIDE
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: 2-SeleniumIDE
